apiVersion: apps/v1
kind: Deployment

metadata:
  name: pagamentos

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: pagamentos

  template:
    metadata:
      labels:
        app: pagamentos

    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        
      containers:
        - name: pagamentos
          image: loja-veloz-pagamentos:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5355