name: CI Loja Veloz

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências - Pedidos
        working-directory: ./pedidos
        run: npm ci

      - name: Instalar dependências - Estoque
        working-directory: ./estoque
        run: npm ci

      - name: Instalar dependências - Pagamentos
        working-directory: ./pagamentos
        run: npm ci

      - name: Instalar dependências - Gateway
        working-directory: ./gateway
        run: npm ci

      - name: Validar código JavaScript
        run: |
          node --check pedidos/index.js
          node --check estoque/index.js
          node --check pagamentos/index.js
          node --check gateway/index.js

      - name: Build das imagens Docker
        run: docker compose build

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publicar imagens no Docker Hub
        run: |
          docker tag loja-veloz-pedidos:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-pedidos:1.0.0
          docker tag loja-veloz-estoque:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-estoque:1.0.0
          docker tag loja-veloz-pagamentos:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-pagamentos:1.0.0
          docker tag loja-veloz-gateway:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-gateway:1.0.0

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-pedidos:1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-estoque:1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-pagamentos:1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loja-veloz-gateway:1.0.0